<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DVA-F0L9N9R-L" name="com.vh.ui.tests.CurrentLabsTest" tests="4" failures="1" timestamp="28 Jun 2017 20:17:47 GMT" time="206.929" errors="0">
  <testcase name="verify_AddAddLabResultsPopupCKD" time="48.936" classname="com.vh.ui.tests.CurrentLabsTest">
    <failure type="java.lang.AssertionError" message="The Add Lab Results popup APPLY THIS DATE TO ALL VALUES was not applied to all dates expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The Add Lab Results popup APPLY THIS DATE TO ALL VALUES was not applied to all dates expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.vh.ui.tests.CurrentLabsTest.verify_AddAddLabResultsPopupCKD(CurrentLabsTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verify_AddAddLabResultsPopupCKD -->
  <testcase name="verify_CurrentLabsPage" time="2.248" classname="com.vh.ui.tests.CurrentLabsTest"/>
  <testcase name="verify_AddLabs" time="36.323" classname="com.vh.ui.tests.CurrentLabsTest"/>
  <testcase name="verify_AddAddLabResultsPopupESRD" time="119.422" classname="com.vh.ui.tests.CurrentLabsTest"/>
</testsuite> <!-- com.vh.ui.tests.CurrentLabsTest -->
