<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="99560" started-at="2017-04-04T19:26:07Z" finished-at="2017-04-04T19:27:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="99560" started-at="2017-04-04T19:26:07Z" finished-at="2017-04-04T19:27:46Z">
      <class name="com.vh.ui.tests.LoginTest">
        <test-method status="PASS" signature="buildUp()[pri:0, instance:com.vh.ui.tests.LoginTest@38cedb7d]" name="buildUp" is-config="true" duration-ms="5528" started-at="2017-04-04T14:26:07Z" finished-at="2017-04-04T14:26:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buildUp -->
        <test-method status="PASS" signature="verify_InvalidUserName()[pri:1, instance:com.vh.ui.tests.LoginTest@38cedb7d]" name="verify_InvalidUserName" duration-ms="24119" started-at="2017-04-04T14:26:13Z" finished-at="2017-04-04T14:26:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_InvalidUserName -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@38cedb7d]" name="afterTest" is-config="true" duration-ms="10" started-at="2017-04-04T14:26:37Z" finished-at="2017-04-04T14:26:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_InvalidUserName() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_InvalidUserName status=SUCCESS method=LoginTest.verify_InvalidUserName()[pri:1, instance:com.vh.ui.tests.LoginTest@38cedb7d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="verify_InvalidPassword()[pri:2, instance:com.vh.ui.tests.LoginTest@38cedb7d]" name="verify_InvalidPassword" duration-ms="15637" started-at="2017-04-04T14:26:37Z" finished-at="2017-04-04T14:26:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_InvalidPassword -->
        <test-method status="PASS" signature="verify_SuccessfulLogin()[pri:3, instance:com.vh.ui.tests.LoginTest@38cedb7d]" name="verify_SuccessfulLogin" duration-ms="51086" started-at="2017-04-04T14:26:52Z" finished-at="2017-04-04T14:27:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_SuccessfulLogin -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@38cedb7d]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-04-04T14:26:52Z" finished-at="2017-04-04T14:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_InvalidPassword() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_InvalidPassword status=SUCCESS method=LoginTest.verify_InvalidPassword()[pri:2, instance:com.vh.ui.tests.LoginTest@38cedb7d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@38cedb7d]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-04-04T14:27:43Z" finished-at="2017-04-04T14:27:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_SuccessfulLogin() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_SuccessfulLogin status=SUCCESS method=LoginTest.verify_SuccessfulLogin()[pri:3, instance:com.vh.ui.tests.LoginTest@38cedb7d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.vh.ui.tests.LoginTest@38cedb7d]" name="tearDown" is-config="true" duration-ms="3105" started-at="2017-04-04T14:27:43Z" finished-at="2017-04-04T14:27:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.vh.ui.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
