<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="83942" started-at="2017-03-28T19:20:52Z" finished-at="2017-03-28T19:22:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="83942" started-at="2017-03-28T19:20:52Z" finished-at="2017-03-28T19:22:16Z">
      <class name="com.vh.ui.tests.LoginTest">
        <test-method status="PASS" signature="buildUp()[pri:0, instance:com.vh.ui.tests.LoginTest@2d760326]" name="buildUp" is-config="true" duration-ms="5710" started-at="2017-03-28T14:20:52Z" finished-at="2017-03-28T14:20:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buildUp -->
        <test-method status="PASS" signature="verify_InvalidUserName()[pri:1, instance:com.vh.ui.tests.LoginTest@2d760326]" name="verify_InvalidUserName" duration-ms="23308" started-at="2017-03-28T14:20:58Z" finished-at="2017-03-28T14:21:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_InvalidUserName -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@2d760326]" name="afterTest" is-config="true" duration-ms="11" started-at="2017-03-28T14:21:22Z" finished-at="2017-03-28T14:21:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_InvalidUserName() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_InvalidUserName status=SUCCESS method=LoginTest.verify_InvalidUserName()[pri:1, instance:com.vh.ui.tests.LoginTest@2d760326] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="verify_InvalidPassword()[pri:2, instance:com.vh.ui.tests.LoginTest@2d760326]" name="verify_InvalidPassword" duration-ms="15878" started-at="2017-03-28T14:21:22Z" finished-at="2017-03-28T14:21:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_InvalidPassword -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@2d760326]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-03-28T14:21:37Z" finished-at="2017-03-28T14:21:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_InvalidPassword() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_InvalidPassword status=SUCCESS method=LoginTest.verify_InvalidPassword()[pri:2, instance:com.vh.ui.tests.LoginTest@2d760326] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="verify_SuccessfulLogin()[pri:3, instance:com.vh.ui.tests.LoginTest@2d760326]" name="verify_SuccessfulLogin" duration-ms="36320" started-at="2017-03-28T14:21:37Z" finished-at="2017-03-28T14:22:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_SuccessfulLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.vh.ui.tests.LoginTest@2d760326]" name="tearDown" is-config="true" duration-ms="2637" started-at="2017-03-28T14:22:14Z" finished-at="2017-03-28T14:22:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterTest(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.vh.ui.tests.LoginTest@2d760326]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-03-28T14:22:14Z" finished-at="2017-03-28T14:22:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vh.ui.tests.LoginTest.verify_SuccessfulLogin() throws com.vh.ui.exceptions.WaitException,com.vh.ui.exceptions.URLNavigationException,java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=verify_SuccessfulLogin status=SUCCESS method=LoginTest.verify_SuccessfulLogin()[pri:3, instance:com.vh.ui.tests.LoginTest@2d760326] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.vh.ui.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
